### ISSUE TITLE
Ver 2.11.0 - Unwinnable seed

### ISSUE THREAD

**Issue by AxelRyman** [thezerothcat/LaMulanaRandomizer#77] opened 2019-02-04 01:26 UTC
1263842316
Only things stopping from me continuing in this current seed is a number of different items or areas. Those include:

Hand Scanner
Bronze Mirror
Life Seal
Death Seal
Spring in the Sky
Chamber of Birth

Problem is that all these involve each other. Like some items are in those areas, or require one of those items to get. Hand Scanner for example is in Chamber of Birth's Perfume Location, and Bronze Mirror is also in Chamber of Birth, while Death Seal is in Isis' Room where I need the scanner. Spring in the Sky is also only accessible via Chamber of Birth. And that's where the problem lies. I have no way into Chamber of Birth.

All the entrances.
Chamber of Birth (Vishnu's Room) <==========> Gate of Time (Surface to Gate of Guidance)
Chamber of Birth (Skanda's Room) <==========> Temple of the Sun (Isis' Anterior Chamber)
Chamber of Birth (Saraswati's Room) <==========> Spring in the Sky (Mural of Oannes)
Chamber of Birth (Deva's Room) <==========> Endless Corridor (Second Endless Corridor)

Gate of Time Surface isn't a way in so  that's out. Spring in the Sky...well that's the only way in(Outside of Mausoleum Pot, but without water that's not a way in either). And Endless Corridor's only activates after talking to the Philsopher in Spring in the Sky...which we already pointed out I can't get to. The last one is Temple of the Sun, which lead's me to Skanda's room...but then I have no way out except Grail...and it's only a one way since after the 1st time, I can't go back through. 

Here's the files.
[gates.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/2826220/gates.txt)
[items.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/2826221/items.txt)
[randomizer-config.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/2826222/randomizer-config.txt)

Seems it might be similar to another issues for Chamber of Birth I saw earlier.

**Comment by thezerothcat** [comment] 2019-02-04 06:48
Based on an external conversation, it seems this was actually against 2.9.0. I was unable to reproduce this seed against newer versions, and the logic looks like the bug with Chamber of Birth fixed in 2.10.0. Closing until/unless the problem comes back on a newer version.

**Closed by thezerothcat** 2019-02-04 06:48 UTC
